import{a as p,S as h,i as d}from"./assets/vendor-Rdv7LHNr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();async function _(s,o=1){const e="https://pixabay.com/api/",r={key:"46129097-db92c21a9f578a732dd89224e",q:encodeURIComponent(s),image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o},n=new URLSearchParams(r);return(await p.get([e,n].join("?"))).data}function v(s){let o="";return s.forEach(e=>{o+=`
      <a class="gallery__item" href="${e.largeImageURL}">
      <figure class="gallery__figure">
        <img class="gallery__img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
        <figcaption class="gallery__figcaption">
          <div class="gallery__caption">Likes: ${e.likes}</div>
          <div class="gallery__caption">Views: ${e.views}</div>
          <div class="gallery__caption">Comments: ${e.comments}</div>
          <div class="gallery__caption">Downloads: ${e.downloads}</div>
    </figcaption>
      </figure>
    </a>`}),o}const g=document.querySelector(".gallery"),L=new h(".gallery .gallery__item"),a=document.querySelector(".loader"),P=document.querySelector("input"),u=document.querySelector("#show-more"),S=document.querySelector(".feedback-form");let i=1,m=0,f=0,c="";const b=15;u.style.display="none";function y(){i=1,m=0,f=0,c="",u.style.display="none"}u.addEventListener("click",function(s){document.querySelector("form button").click()});S.addEventListener("submit",function(s){s.preventDefault(),a.style.display="block";const o=P.value.trim();if(o===""){a.style.display="none",d.error({title:"Error",message:"Please enter a search query!"});return}c!=o&&(y(),g.innerHTML="",c=o),_(c,i).then(e=>{if(e.totalHits&&e.totalHits>0){m=e.totalHits,f=Math.ceil(m/b);const l=e.hits,t=v(l);g.innerHTML+=t;let n=document.querySelector("a.gallery__item").getBoundingClientRect().height*2;i!=1&&window.scrollBy({top:n,behavior:"smooth"}),L.refresh(),i==f?(y(),d.error({title:"Info",message:"We're sorry, but you've reached the end of search results."})):(u.style.display="block",i++)}else y(),d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});a.style.display="none"}).catch(e=>{a.style.display="none",console.log(e.message)})});
//# sourceMappingURL=index.js.map
