import{a as h,S as _,i as l}from"./assets/vendor-Rdv7LHNr.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();async function v(a,r=1){const o="https://pixabay.com/api/",t={key:"46129097-db92c21a9f578a732dd89224e",q:encodeURIComponent(a),image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r},n=new URLSearchParams(t);return(await h.get([o,n].join("?"))).data}function L(a){let r="";return a.forEach(o=>{r+=`
      <a class="gallery__item" href="${o.largeImageURL}">
      <figure class="gallery__figure">
        <img class="gallery__img" src="${o.webformatURL}" alt="${o.tags}" loading="lazy">
        <figcaption class="gallery__figcaption">
          <div class="gallery__caption">Likes: ${o.likes}</div>
          <div class="gallery__caption">Views: ${o.views}</div>
          <div class="gallery__caption">Comments: ${o.comments}</div>
          <div class="gallery__caption">Downloads: ${o.downloads}</div>
    </figcaption>
      </figure>
    </a>`}),r}const p=document.querySelector(".gallery"),w=new _(".gallery .gallery__item"),c=document.querySelector(".loader"),P=document.querySelector("input"),d=document.querySelector("#show-more"),S=document.querySelector(".feedback-form");let i=1,m=0,f=0,u="";const b=15;d.style.display="none";function y(){i=1,m=0,f=0,u="",d.style.display="none"}d.addEventListener("click",function(a){document.querySelector("form button").click()});S.addEventListener("submit",function(a){a.preventDefault(),c.style.display="block";const r=P.value.trim();if(r===""){c.style.display="none",l.error({title:"Error",message:"Please enter a search query!"});return}u!=r&&(y(),p.innerHTML="",u=r),(async()=>{try{const s=await v(u,i);if(s.totalHits&&s.totalHits>0){m=s.totalHits,f=Math.ceil(m/b);const e=s.hits,t=L(e);p.innerHTML+=t;let g=document.querySelector("a.gallery__item").getBoundingClientRect().height*2;i!=1&&window.scrollBy({top:g,behavior:"smooth"}),w.refresh(),i==f?(y(),l.error({title:"Info",message:"We're sorry, but you've reached the end of search results."})):(d.style.display="block",i++)}else y(),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});c.style.display="none"}catch{c.style.display="none",l.error({title:"Error",message:"Error!"})}})()});
//# sourceMappingURL=index.js.map
